before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: mackerel-plugin-prometheus-exporter
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  ldflags:
    - -s -w -X github.com/k1LoW/mackerel-plugin-prometheus-exporter.version={{.Version}} -X github.com/k1LoW/mackerel-plugin-prometheus-exporter.commit={{.FullCommit}} -X github.com/k1LoW/mackerel-plugin-prometheus-exporter.date={{.Date}} -X github.com/k1LoW/mackerel-plugin-prometheus-exporter/version.Version={{.Version}}
archives:
-
  id: mackerel-plugin-prometheus-exporter-release
  name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: zip
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
-
  id: mackerel-plugin-prometheus-exporter-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
